//
// Created by Alex Python on 11/27/17.
//

#ifndef COMP220BOOKSTORE_INVENTORYMANAGER_H
#define COMP220BOOKSTORE_INVENTORYMANAGER_H

class InventoryManager{};

#endif //COMP220BOOKSTORE_INVENTORYMANAGER_H
